# ESPHome ArcadePad S3
# esphome-web-c1e054
# File Description: External Package

# [ ==== Binary Sensors (Arcade Buttons) ==== ] #
binary_sensor:
  - platform: gpio
    id: arcadepad_s3_key_1
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
      inverted: true
    name: "ArcadePad S3 Key 1"
    icon: mdi:gamepad-circle
    internal: true
    on_press:
      - lambda: |-
          id(arcadepad_s3_key_1_count) += 1;
          id(arcadepad_s3_key_1_presses_today).publish_state(id(arcadepad_s3_key_1_count));
          
          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d", 
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(arcadepad_s3_key_1_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 100%
          green: 0%
          blue: 0%
          brightness: 100%
          effect: "none"
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.bathroom_lights_switch
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%

  - platform: gpio
    id: arcadepad_s3_key_2
    pin:
      number: GPIO5
      mode:
        input: true
        pullup: true
      inverted: true
    name: "ArcadePad S3 Key 2"
    icon: mdi:gamepad-circle-up
    internal: true
    on_press:
      - lambda: |-
          id(arcadepad_s3_key_2_count) += 1;
          id(arcadepad_s3_key_2_presses_today).publish_state(id(arcadepad_s3_key_2_count));
          
          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d", 
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(arcadepad_s3_key_2_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 100%
          green: 50%
          blue: 0%
          brightness: 100%
          effect: "none"
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.bathroom_lights_switch
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%

  - platform: gpio
    id: arcadepad_s3_key_3
    pin:
      number: GPIO6
      mode:
        input: true
        pullup: true
      inverted: true
    name: "ArcadePad S3 Key 3"
    icon: mdi:gamepad-circle-right
    internal: true
    on_press:
      - lambda: |-
          id(arcadepad_s3_key_3_count) += 1;
          id(arcadepad_s3_key_3_presses_today).publish_state(id(arcadepad_s3_key_3_count));
          
          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d", 
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(arcadepad_s3_key_3_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 100%
          green: 100%
          blue: 0%
          brightness: 100%
          effect: "none"
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.bathroom_lights_switch
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%

  - platform: gpio
    id: arcadepad_s3_key_4
    pin:
      number: GPIO7
      mode:
        input: true
        pullup: true
      inverted: true
    name: "ArcadePad S3 Key 4"
    icon: mdi:nintendo-game-boy
    internal: true
    on_press:
      - lambda: |-
          id(arcadepad_s3_key_4_count) += 1;
          id(arcadepad_s3_key_4_presses_today).publish_state(id(arcadepad_s3_key_4_count));
          
          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d", 
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(arcadepad_s3_key_4_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 0%
          green: 100%
          blue: 0%
          brightness: 100%
          effect: "none"
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.bathroom_lights_switch
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%

  - platform: gpio
    id: arcadepad_s3_key_5
    pin:
      number: GPIO15
      mode:
        input: true
        pullup: true
      inverted: true
    name: "ArcadePad S3 Key 5"
    icon: mdi:gamepad-circle-down
    internal: true
    on_press:
      - lambda: |-
          id(arcadepad_s3_key_5_count) += 1;
          id(arcadepad_s3_key_5_presses_today).publish_state(id(arcadepad_s3_key_5_count));
          
          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d", 
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(arcadepad_s3_key_5_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 0%
          green: 100%
          blue: 100%
          brightness: 100%
          effect: "none"
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.bathroom_lights_switch
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%

  - platform: gpio
    id: arcadepad_s3_key_6
    pin:
      number: GPIO16
      mode:
        input: true
        pullup: true
      inverted: true
    name: "ArcadePad S3 Key 6"
    icon: mdi:gamepad-circle-left
    internal: true
    on_press:
      - lambda: |-
          id(arcadepad_s3_key_6_count) += 1;
          id(arcadepad_s3_key_6_presses_today).publish_state(id(arcadepad_s3_key_6_count));
          
          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d", 
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(arcadepad_s3_key_6_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 0%
          green: 0%
          blue: 100%
          brightness: 100%
          effect: "none"
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.bathroom_lights_switch
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%

  - platform: gpio
    id: arcadepad_s3_key_7
    pin:
      number: GPIO17
      mode:
        input: true
        pullup: true
      inverted: true
    name: "ArcadePad S3 Key 7"
    icon: mdi:gamepad-circle-outline
    internal: true
    on_press:
      - lambda: |-
          id(arcadepad_s3_key_7_count) += 1;
          id(arcadepad_s3_key_7_presses_today).publish_state(id(arcadepad_s3_key_7_count));
          
          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d", 
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(arcadepad_s3_key_7_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 50%
          green: 0%
          blue: 100%
          brightness: 100%
          effect: "none"
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.bathroom_lights_switch
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%
# ESP32 Boot Button
#  - platform: gpio
#    pin:
#      number: GPIO0
#      ignore_strapping_warning: true
#      inverted: true
#      mode:
#        input: true
#        pullup: true
#    name: "ArcadePad S3 Boot Button"
#    icon: mdi:gesture-tap-button
