# ESPHome MacroPad S3
# esphome-web-c32654 Version 3
# File Description: External Package

# [ ==== Time Info ==== ] #
time:
  - platform: homeassistant
    id: ha_time
    timezone: "America/Chicago"

# [ ==== Matrix Keypad Configuration ==== ]
matrix_keypad:
  id: macropad_s3_keypad
  rows:
    - pin:
        number: GPIO8
        mode: { output: true }
    - pin:
        number: GPIO9
        mode: { output: true }
    - pin:
        number: GPIO10
        mode: { output: true }
  columns:
    - pin:
        number: GPIO11
        mode: { input: true, pullup: true }
    - pin:
        number: GPIO12
        mode: { input: true, pullup: true }
    - pin:
        number: GPIO13
        mode: { input: true, pullup: true }
  keys: "123456789"
  has_diodes: false

# [ ==== Globals Info ==== ] #
# globals: [PLACEHOLDER]

# [ ==== Sensor Info ==== ] #
# sensor: [PLACEHOLDER]

# [ ==== Binary Sensors ==== ]
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      ignore_strapping_warning: true
      inverted: true
      mode: { input: true, pullup: true }
    name: "Boot Button - MacroPad S3"
    icon: mdi:gesture-tap-button

  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: key_1_macropad_s3
    key: "1"
    name: "Key 1 - MacroPad S3"
    on_press:
      - script.execute:
          id: handle_key_action
          key_num: 1
    on_release:
      - script.execute: reset_led_to_rainbow
    on_click:
      - min_length: 2s
        max_length: 5s
        then:
          - script.execute:
              id: handle_key_hold_action
              key_num: 1

  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: key_2_macropad_s3
    key: "2"
    name: "Key 2 - MacroPad S3"
    on_press:
      - script.execute:
          id: handle_key_action
          key_num: 2
    on_release:
      - script.execute: reset_led_to_rainbow
    on_click:
      - min_length: 2s
        max_length: 5s
        then:
          - script.execute:
              id: handle_key_hold_action
              key_num: 2

  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: key_3_macropad_s3
    key: "3"
    name: "Key 3 - MacroPad S3"
    on_press:
      - script.execute:
          id: handle_key_action
          key_num: 3
    on_release:
      - script.execute: reset_led_to_rainbow
    on_click:
      - min_length: 2s
        max_length: 5s
        then:
          - script.execute:
              id: handle_key_hold_action
              key_num: 3

  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: key_4_macropad_s3
    key: "4"
    name: "Key 4 - MacroPad S3"
    on_press:
      - script.execute:
          id: handle_key_action
          key_num: 4
    on_release:
      - script.execute: reset_led_to_rainbow
    on_click:
      - min_length: 2s
        max_length: 5s
        then:
          - script.execute:
              id: handle_key_hold_action
              key_num: 4

  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: key_5_macropad_s3
    key: "5"
    name: "Key 5 - MacroPad S3"
    on_press:
      - script.execute:
          id: handle_key_action
          key_num: 5
    on_release:
      - script.execute: reset_led_to_rainbow
    on_click:
      - min_length: 2s
        max_length: 5s
        then:
          - script.execute:
              id: handle_key_hold_action
              key_num: 5

  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: key_6_macropad_s3
    key: "6"
    name: "Key 6 - MacroPad S3"
    on_press:
      - script.execute:
          id: handle_key_action
          key_num: 6
    on_release:
      - script.execute: reset_led_to_rainbow
    on_click:
      - min_length: 2s
        max_length: 5s
        then:
          - script.execute:
              id: handle_key_hold_action
              key_num: 6

  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: key_7_macropad_s3
    key: "7"
    name: "Key 7 - MacroPad S3"
    on_press:
      - script.execute:
          id: handle_key_action
          key_num: 7
    on_release:
      - script.execute: reset_led_to_rainbow
    on_click:
      - min_length: 2s
        max_length: 5s
        then:
          - script.execute:
              id: handle_key_hold_action
              key_num: 7

  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: key_8_macropad_s3
    key: "8"
    name: "Key 8 - MacroPad S3"
    on_press:
      - script.execute:
          id: handle_key_action
          key_num: 8
    on_release:
      - script.execute: reset_led_to_rainbow
    on_click:
      - min_length: 2s
        max_length: 5s
        then:
          - script.execute:
              id: handle_key_hold_action
              key_num: 8

  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: key_9_macropad_s3
    key: "9"
    name: "Key 9 - MacroPad S3"
    on_press:
      - script.execute:
          id: handle_key_action
          key_num: 9
    on_release:
      - script.execute: reset_led_to_rainbow
    on_click:
      - min_length: 2s
        max_length: 5s
        then:
          - script.execute:
              id: handle_key_hold_action
              key_num: 9

# [ ==== Text Sensor Info ==== ] #
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address - MacroPad S3"
      icon: mdi:ip-network
  - platform: version
    name: "ESPHome Version - MacroPad S3"
    icon: mdi:car-esp

# [ ==== Script Info ==== ] #
script:
  - id: handle_key_action
    parameters:
      key_num: int
    then:
      # Set LED to white on press
      - light.turn_on:
          id: rgb_led
          red: 100%
          green: 100%
          blue: 100%
          brightness: 100%
          effect: none
      # Execute Home Assistant action
      - homeassistant.action:
          action: !lambda |-
            switch(key_num) {
              case 1: return "${key_1_action}";
              case 2: return "${key_2_action}";
              case 3: return "${key_3_action}";
              case 4: return "${key_4_action}";
              case 5: return "${key_5_action}";
              case 6: return "${key_6_action}";
              case 7: return "${key_7_action}";
              case 8: return "${key_8_action}";
              case 9: return "${key_9_action}";
            }
            return "";
          data:
            entity_id: !lambda |-
              switch(key_num) {
                case 1: return "${key_1_entity}";
                case 2: return "${key_2_entity}";
                case 3: return "${key_3_entity}";
                case 4: return "${key_4_entity}";
                case 5: return "${key_5_entity}";
                case 6: return "${key_6_entity}";
                case 7: return "${key_7_entity}";
                case 8: return "${key_8_entity}";
                case 9: return "${key_9_entity}";
              }
              return "";

  - id: handle_key_hold_action
    parameters:
      key_num: int
    then:
      # Set LED to blue on hold
      - light.turn_on:
          id: rgb_led
          red: 0%
          green: 20%
          blue: 100%
          brightness: 100%
          effect: none
      # Execute Home Assistant hold action
      - homeassistant.action:
          action: !lambda |-
            switch(key_num) {
              case 1: return "${key_1_action_hold}";
              case 2: return "${key_2_action_hold}";
              case 3: return "${key_3_action_hold}";
              case 4: return "${key_4_action_hold}";
              case 5: return "${key_5_action_hold}";
              case 6: return "${key_6_action_hold}";
              case 7: return "${key_7_action_hold}";
              case 8: return "${key_8_action_hold}";
              case 9: return "${key_9_action_hold}";
            }
            return "";
          data:
            entity_id: !lambda |-
              switch(key_num) {
                case 1: return "${key_1_entity_hold}";
                case 2: return "${key_2_entity_hold}";
                case 3: return "${key_3_entity_hold}";
                case 4: return "${key_4_entity_hold}";
                case 5: return "${key_5_entity_hold}";
                case 6: return "${key_6_entity_hold}";
                case 7: return "${key_7_entity_hold}";
                case 8: return "${key_8_entity_hold}";
                case 9: return "${key_9_entity_hold}";
              }
              return "";

  - id: reset_led_to_rainbow
    mode: restart
    then:
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 100%
