# [ ==== ESP Home Info ==== ] #
esphome:
  name: esphome-web-c32654
  friendly_name: ESPHome Macro Keypad
  min_version: 2025.9.0
  name_add_mac_suffix: false

# [ ==== PCB Board Info ==== ] #
esp32:
  variant: esp32s3
  framework:
    type: esp-idf

# [ ==== Logging, API, and Updates ==== ] #
logger:
api:
ota:
  - platform: esphome

# [ ==== WiFi Info ==== ] #
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  on_connect:
    then:
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%
#          red: 0%
#          green: 50%
#          blue: 50%
#      - delay: 10s
#      - light.turn_off:
#          id: rgb_led
  on_disconnect:
    then:
      - light.turn_on:
          id: rgb_led
          effect: pulse
          red: 100%
          green: 0%
          blue: 0%
          brightness: 100%

# [ ==== Web Server Info ==== ] #
web_server:
  port: 80
  version: 3

# [ ==== Time Configuration ==== ] #
time:
  - platform: homeassistant
    id: ha_time
    timezone: "America/Chicago"
    on_time:
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - lambda: |-
              id(key_1_count) = 0;
              id(key_2_count) = 0;
              id(key_3_count) = 0;
              id(key_4_count) = 0;
              id(key_5_count) = 0;
              id(key_6_count) = 0;
              id(key_7_count) = 0;
              id(key_8_count) = 0;
              id(key_9_count) = 0;
              id(key_1_presses_today).publish_state(0);
              id(key_2_presses_today).publish_state(0);
              id(key_3_presses_today).publish_state(0);
              id(key_4_presses_today).publish_state(0);
              id(key_5_presses_today).publish_state(0);
              id(key_6_presses_today).publish_state(0);
              id(key_7_presses_today).publish_state(0);
              id(key_8_presses_today).publish_state(0);
              id(key_9_presses_today).publish_state(0);

# [ ==== External Packages ==== ] #
packages:
 remote_package_files:
   url: https://github.com/SpicyLimes/ESP32-S3-Files
   files: YAML-Configs/ESP32-S2_c32654-Package_v1.yaml
   ref: main
   refresh: 5min
