# ESPHome Macro Keypad
# esphome-web-c32654
# File Description: External Package

# [ ==== Matrix Keypad Configuration ==== ] #
matrix_keypad:
  id: keypad
  rows:
    - pin: 
        number: GPIO1    # Row 1
        mode:
          output: true
    - pin: 
        number: GPIO2    # Row 2
        mode:
          output: true
    - pin: 
        number: GPIO42   # Row 3
        mode:
          output: true
  columns:
    - pin: 
        number: GPIO41   # Column 1
        mode:
          input: true
          pullup: true
    - pin: 
        number: GPIO40   # Column 2
        mode:
          input: true
          pullup: true
    - pin: 
        number: GPIO39   # Column 3
        mode:
          input: true
          pullup: true
  keys: "123456789"
  has_diodes: false

# [ ==== Binary Sensors for Each Key ==== ] #
binary_sensor:
- platform: matrix_keypad
    keypad_id: keypad
    id: key_1
    key: "1"
    name: "Key 1"
    on_press:
      - lambda: |-
          id(key_1_count) += 1;
          id(key_1_presses_today).publish_state(id(key_1_count));
          
          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d", 
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(key_1_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 100%
          green: 0%
          blue: 0%
          brightness: 100%
          effect: "none"
      - homeassistant.service:
          service: light.toggle
          data:
            entity_id: light.kitchen_lights_switch
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%

  - platform: matrix_keypad
    keypad_id: keypad
    id: key_2
    key: "2"
    name: "Key 2"
    on_press:
      - lambda: |-
          id(key_2_count) += 1;
          id(key_2_presses_today).publish_state(id(key_2_count));
          
          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d", 
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(key_2_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 100%
          green: 50%
          blue: 0%
          brightness: 100%
          effect: "none"
      - homeassistant.service:
          service: light.toggle
          data:
            entity_id: light.bar_lights
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%

  - platform: matrix_keypad
    keypad_id: keypad
    id: key_3
    key: "3"
    name: "Key 3"
    on_press:
      - lambda: |-
          id(key_3_count) += 1;
          id(key_3_presses_today).publish_state(id(key_3_count));
          
          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d", 
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(key_3_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 100%
          green: 100%
          blue: 0%
          brightness: 100%
          effect: "none"
      - homeassistant.service:
          service: light.toggle
          data:
            entity_id: light.studio_lights
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%

  - platform: matrix_keypad
    keypad_id: keypad
    id: key_4
    key: "4"
    name: "Key 4"
    on_press:
      - lambda: |-
          id(key_4_count) += 1;
          id(key_4_presses_today).publish_state(id(key_4_count));
          
          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d", 
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(key_4_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 0%
          green: 100%
          blue: 0%
          brightness: 100%
          effect: "none"
      - homeassistant.service:
          service: light.toggle
          data:
            entity_id: light.office_lights_leds
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%

  - platform: matrix_keypad
    keypad_id: keypad
    id: key_5
    key: "5"
    name: "Key 5"
    on_press:
      - lambda: |-
          id(key_5_count) += 1;
          id(key_5_presses_today).publish_state(id(key_5_count));
          
          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d", 
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(key_5_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 0%
          green: 100%
          blue: 100%
          brightness: 100%
          effect: "none"
      - homeassistant.service:
          service: light.toggle
          data:
            entity_id: light.bathroom_lights_switch
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%

  - platform: matrix_keypad
    keypad_id: keypad
    id: key_6
    key: "6"
    name: "Key 6"
    on_press:
      - lambda: |-
          id(key_6_count) += 1;
          id(key_6_presses_today).publish_state(id(key_6_count));
          
          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d", 
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(key_6_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 0%
          green: 0%
          blue: 100%
          brightness: 100%
          effect: "none"
      - homeassistant.service:
          service: light.toggle
          data:
            entity_id: light.closet_lights_switch
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%

  - platform: matrix_keypad
    keypad_id: keypad
    id: key_7
    key: "7"
    name: "Key 7"
    on_press:
      - lambda: |-
          id(key_7_count) += 1;
          id(key_7_presses_today).publish_state(id(key_7_count));
          
          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d", 
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(key_7_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 50%
          green: 0%
          blue: 100%
          brightness: 100%
          effect: "none"
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.studio_and_office_miami_vice_lights
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%

  - platform: matrix_keypad
    keypad_id: keypad
    id: key_8
    key: "8"
    name: "Key 8"
    on_press:
      - lambda: |-
          id(key_8_count) += 1;
          id(key_8_presses_today).publish_state(id(key_8_count));
          
          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d", 
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(key_8_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 100%
          green: 0%
          blue: 50%
          brightness: 100%
          effect: "none"
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.night_light_studio
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%

  - platform: matrix_keypad
    keypad_id: keypad
    id: key_9
    key: "9"
    name: "Key 9"
    on_press:
      - lambda: |-
          id(key_9_count) += 1;
          id(key_9_presses_today).publish_state(id(key_9_count));
          
          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d", 
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(key_9_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 100%
          green: 100%
          blue: 100%
          brightness: 100%
          effect: "none"
      - homeassistant.service:
          service: light.turn_off
          data:
            entity_id: light.apartment_lights
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%
