# [ ==== esphome-web-c1e054.yaml ==== ] #
esphome:
  name: esphome-web-c1e054 # Version 2
  friendly_name: ESPHome ArcadePad S3
  min_version: 2025.10.0
  name_add_mac_suffix: false

# [ ==== PCB Board Info ==== ] #
esp32:
  variant: esp32s3
  framework:
    type: esp-idf

# [ ==== Logging, API, and Updates ==== ] #
logger:
api:
ota:
  - platform: esphome

# [ ==== WiFi Info ==== ] #
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  on_connect:
    then:
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 100%
  on_disconnect:
    then:
      - light.turn_on:
          id: rgb_led
          effect: pulse
          red: 100%
          green: 0%
          blue: 0%
          brightness: 100%

# [ ==== RGB LED (WS2812B) Info ==== ] #
light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO48
    num_leds: 1
    chipset: WS2812
    name: "RGB LED - ArcadePad S3"
    id: rgb_led
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 0.15s
    icon: mdi:led-on
    effects:
      - pulse:
      - strobe:
      - flicker:
      - addressable_rainbow:

# [ ==== Substitutions ==== ] #
substitutions:
  # Entities
  key_1_entity: "light.bathroom_lights_switch" # 
  key_2_entity: "light.bathroom_lights_switch" # 
  key_3_entity: "light.bathroom_lights_switch" # 
  key_4_entity: "light.bathroom_lights_switch" # 
  key_5_entity: "light.bathroom_lights_switch" # 
  key_6_entity: "light.bathroom_lights_switch" # 
  key_7_entity: "light.bathroom_lights_switch" # 
  key_1_entity_hold: "light.closet_lights_switch" # 
  key_2_entity_hold: "light.closet_lights_switch" # 
  key_3_entity_hold: "light.closet_lights_switch" # 
  key_4_entity_hold: "light.closet_lights_switch" # 
  key_5_entity_hold: "light.closet_lights_switch" # 
  key_6_entity_hold: "light.closet_lights_switch" # 
  key_7_entity_hold: "light.closet_lights_switch" # 
  # Actions
  key_1_action: "light.toggle" # 
  key_2_action: "light.toggle" # 
  key_3_action: "light.toggle" # 
  key_4_action: "light.toggle" # 
  key_5_action: "light.toggle" # 
  key_6_action: "light.toggle" # 
  key_7_action: "light.toggle" # 
  key_1_action_hold: "light.toggle" # 
  key_2_action_hold: "light.toggle" # 
  key_3_action_hold: "light.toggle" # 
  key_4_action_hold: "light.toggle" # 
  key_5_action_hold: "light.toggle" # 
  key_6_action_hold: "light.toggle" # 
  key_7_action_hold: "light.toggle" # 

# [ ==== External Packages ==== ] #
packages:
 remote_package_files:
   url: https://github.com/SpicyLimes/ESP32-S3-Files
   files: YAML-Configs/ESP32-S3_c1e054-Package_v2.yaml
   ref: main
   refresh: 0s
