# [ ==== ESP Home Info ==== ] #
esphome:
  name: esphome-web-c32654
  friendly_name: ESPHome Macro Keypad
  min_version: 2025.9.0
  name_add_mac_suffix: false

# [ ==== PCB Board Info ==== ] #
esp32:
  variant: esp32s3
  framework:
    type: esp-idf

# [ ==== Logging, API, and Updates ==== ] #
logger:
api:
ota:
  - platform: esphome

# [ ==== WiFi Info ==== ] #
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  on_connect:
    then:
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 50%
#          red: 0%
#          green: 50%
#          blue: 50%
#      - delay: 10s
#      - light.turn_off:
#          id: rgb_led
  on_disconnect:
    then:
      - light.turn_on:
          id: rgb_led
          effect: pulse
          red: 100%
          green: 0%
          blue: 0%
          brightness: 100%

# [ ==== Web Server Info ==== ] #
web_server:
  port: 80
  version: 3

# [ ==== Time Configuration ==== ] #
time:
  - platform: homeassistant
    id: ha_time
    timezone: "America/Chicago"
    on_time:
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - lambda: |-
              id(key_1_count) = 0;
              id(key_2_count) = 0;
              id(key_3_count) = 0;
              id(key_4_count) = 0;
              id(key_5_count) = 0;
              id(key_6_count) = 0;
              id(key_7_count) = 0;
              id(key_8_count) = 0;
              id(key_9_count) = 0;
              id(key_1_presses_today).publish_state(0);
              id(key_2_presses_today).publish_state(0);
              id(key_3_presses_today).publish_state(0);
              id(key_4_presses_today).publish_state(0);
              id(key_5_presses_today).publish_state(0);
              id(key_6_presses_today).publish_state(0);
              id(key_7_presses_today).publish_state(0);
              id(key_8_presses_today).publish_state(0);
              id(key_9_presses_today).publish_state(0);

# [ ==== Button Press Tracking ==== ] #
globals:
  - id: key_1_count
    type: int
    restore_value: no
    initial_value: '0'
  - id: key_2_count
    type: int
    restore_value: no
    initial_value: '0'
  - id: key_3_count
    type: int
    restore_value: no
    initial_value: '0'
  - id: key_4_count
    type: int
    restore_value: no
    initial_value: '0'
  - id: key_5_count
    type: int
    restore_value: no
    initial_value: '0'
  - id: key_6_count
    type: int
    restore_value: no
    initial_value: '0'
  - id: key_7_count
    type: int
    restore_value: no
    initial_value: '0'
  - id: key_8_count
    type: int
    restore_value: no
    initial_value: '0'
  - id: key_9_count
    type: int
    restore_value: no
    initial_value: '0'

# [ ==== Buttons ==== ] #
button:
  - platform: factory_reset
    name: Factory Reset

# [ ==== Sensors ==== ] #
sensor:
  - platform: template
    name: "Key 1 Presses Today"
    id: key_1_presses_today
    icon: mdi:counter
    accuracy_decimals: 0
    update_interval: never
    lambda: 'return id(key_1_count);'
  - platform: template
    name: "Key 2 Presses Today"
    id: key_2_presses_today
    icon: mdi:counter
    accuracy_decimals: 0
    update_interval: never
    lambda: 'return id(key_2_count);'
  - platform: template
    name: "Key 3 Presses Today"
    id: key_3_presses_today
    icon: mdi:counter
    accuracy_decimals: 0
    update_interval: never
    lambda: 'return id(key_3_count);'
  - platform: template
    name: "Key 4 Presses Today"
    id: key_4_presses_today
    icon: mdi:counter
    accuracy_decimals: 0
    update_interval: never
    lambda: 'return id(key_4_count);'
  - platform: template
    name: "Key 5 Presses Today"
    id: key_5_presses_today
    icon: mdi:counter
    accuracy_decimals: 0
    update_interval: never
    lambda: 'return id(key_5_count);'
  - platform: template
    name: "Key 6 Presses Today"
    id: key_6_presses_today
    icon: mdi:counter
    accuracy_decimals: 0
    update_interval: never
    lambda: 'return id(key_6_count);'
  - platform: template
    name: "Key 7 Presses Today"
    id: key_7_presses_today
    icon: mdi:counter
    accuracy_decimals: 0
    update_interval: never
    lambda: 'return id(key_7_count);'
  - platform: template
    name: "Key 8 Presses Today"
    id: key_8_presses_today
    icon: mdi:counter
    accuracy_decimals: 0
    update_interval: never
    lambda: 'return id(key_8_count);'
  - platform: template
    name: "Key 9 Presses Today"
    id: key_9_presses_today
    icon: mdi:counter
    accuracy_decimals: 0
    update_interval: never
    lambda: 'return id(key_9_count);'

# [ ==== Text Sensors ==== ] #
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "ESP32-S3 IP Address"
  - platform: version
    name: "ESPHome Version"
  - platform: template
    name: "Key 1 Last Pressed"
    id: key_1_last_pressed
    icon: mdi:clock-outline
    update_interval: never
  - platform: template
    name: "Key 2 Last Pressed"
    id: key_2_last_pressed
    icon: mdi:clock-outline
    update_interval: never
  - platform: template
    name: "Key 3 Last Pressed"
    id: key_3_last_pressed
    icon: mdi:clock-outline
    update_interval: never
  - platform: template
    name: "Key 4 Last Pressed"
    id: key_4_last_pressed
    icon: mdi:clock-outline
    update_interval: never
  - platform: template
    name: "Key 5 Last Pressed"
    id: key_5_last_pressed
    icon: mdi:clock-outline
    update_interval: never
  - platform: template
    name: "Key 6 Last Pressed"
    id: key_6_last_pressed
    icon: mdi:clock-outline
    update_interval: never
  - platform: template
    name: "Key 7 Last Pressed"
    id: key_7_last_pressed
    icon: mdi:clock-outline
    update_interval: never
  - platform: template
    name: "Key 8 Last Pressed"
    id: key_8_last_pressed
    icon: mdi:clock-outline
    update_interval: never
  - platform: template
    name: "Key 9 Last Pressed"
    id: key_9_last_pressed
    icon: mdi:clock-outline
    update_interval: never

# [ ==== Binary Sensors ==== ] #
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0  # ESP32 Boot Button
      ignore_strapping_warning: true
      inverted: true
      mode:
        input: true
        pullup: true
    name: "ESP32-S3 Boot Button"

# [ ==== Addressable RGB LED (NeoPixel/WS2812B) ==== ] #
light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO48
    num_leds: 1
    chipset: WS2812
    name: "ESP32-S3 RGB LED"
    id: rgb_led
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 0.5s
    effects:
      - pulse:
      - strobe:
      - flicker:
      - addressable_rainbow:

# [ ==== External Packages ==== ] #
packages:
 remote_package_files:
   url: https://github.com/SpicyLimes/ESP32-S3-Files
   files: YAML-Configs/ESP32-S2_c32654-Package_v1.yaml
   ref: main
   refresh: 5min
