# ESPHome MacroPad S3
# esphome-web-c32654
# File Description: External Package

# [ ==== Matrix Keypad Configuration ==== ] #
matrix_keypad:
  id: macropad_s3_keypad
  rows:
    - pin:
        number: GPIO8    # Row 1
        mode:
          output: true
    - pin:
        number: GPIO9    # Row 2
        mode:
          output: true
    - pin:
        number: GPIO10   # Row 3
        mode:
          output: true
  columns:
    - pin:
        number: GPIO11   # Column 1
        mode:
          input: true
          pullup: true
    - pin:
        number: GPIO12   # Column 2
        mode:
          input: true
          pullup: true
    - pin:
        number: GPIO13   # Column 3
        mode:
          input: true
          pullup: true
  keys: "123456789"
  has_diodes: false

# [ ==== Binary Sensors ==== ] #
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0  # ESP32 Boot Button
      ignore_strapping_warning: true
      inverted: true
      mode:
        input: true
        pullup: true
    name: "MacroPad S3 Boot Button"
  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: macropad_s3_key_1
    key: "1"
    name: "MacroPad S3 Key 1"
    on_press:
      - lambda: |-
          id(macropad_s3_key_1_count) += 1;
          id(macropad_s3_key_1_presses_today).publish_state(id(macropad_s3_key_1_count));

          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d",
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(macropad_s3_key_1_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 100%
          green: 0%
          blue: 0%
          brightness: 100%
          effect: "none"
      - homeassistant.action:
          action: assist_satellite.announce
          data:
            message: "Button 1 Pressed"
            preannounce: "false"
            entity_id: assist_satellite.home_assistant_voice_09bf3e_assist_satellite # <-- entity_id moved under data:
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 100%

  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: macropad_s3_key_2
    key: "2"
    name: "MacroPad S3 Key 2"
    on_press:
      - lambda: |-
          id(macropad_s3_key_2_count) += 1;
          id(macropad_s3_key_2_presses_today).publish_state(id(macropad_s3_key_2_count));

          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d",
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(macropad_s3_key_2_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 100%
          green: 50%
          blue: 0%
          brightness: 100%
          effect: "none"
      - homeassistant.action:
          action: assist_satellite.announce
          data:
            message: "Button 2 Pressed"
            preannounce: "false"
            entity_id: assist_satellite.home_assistant_voice_09bf3e_assist_satellite # <-- entity_id moved under data:
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 100%

  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: macropad_s3_key_3
    key: "3"
    name: "MacroPad S3 Key 3"
    on_press:
      - lambda: |-
          id(macropad_s3_key_3_count) += 1;
          id(macropad_s3_key_3_presses_today).publish_state(id(macropad_s3_key_3_count));

          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d",
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(macropad_s3_key_3_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 100%
          green: 100%
          blue: 0%
          brightness: 100%
          effect: "none"
      - homeassistant.action:
          action: assist_satellite.announce
          data:
            message: "Button 3 Pressed"
            preannounce: "false"
            entity_id: assist_satellite.home_assistant_voice_09bf3e_assist_satellite # <-- entity_id moved under data:
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 100%

  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: macropad_s3_key_4
    key: "4"
    name: "MacroPad S3 Key 4"
    on_press:
      - lambda: |-
          id(macropad_s3_key_4_count) += 1;
          id(macropad_s3_key_4_presses_today).publish_state(id(macropad_s3_key_4_count));

          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d",
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(macropad_s3_key_4_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 0%
          green: 100%
          blue: 0%
          brightness: 100%
          effect: "none"
      - homeassistant.action:
          action: assist_satellite.announce
          data:
            message: "Button 4 Pressed"
            preannounce: "false"
            entity_id: assist_satellite.home_assistant_voice_09bf3e_assist_satellite # <-- entity_id moved under data:
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 100%

  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: macropad_s3_key_5
    key: "5"
    name: "MacroPad S3 Key 5"
    on_press:
      - lambda: |-
          id(macropad_s3_key_5_count) += 1;
          id(macropad_s3_key_5_presses_today).publish_state(id(macropad_s3_key_5_count));

          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d",
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(macropad_s3_key_5_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 0%
          green: 100%
          blue: 100%
          brightness: 100%
          effect: "none"
      - homeassistant.action:
          action: assist_satellite.announce
          data:
            message: "Button 5 Pressed"
            preannounce: "false"
            entity_id: assist_satellite.home_assistant_voice_09bf3e_assist_satellite # <-- entity_id moved under data:
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 100%

  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: macropad_s3_key_6
    key: "6"
    name: "MacroPad S3 Key 6"
    on_press:
      - lambda: |-
          id(macropad_s3_key_6_count) += 1;
          id(macropad_s3_key_6_presses_today).publish_state(id(macropad_s3_key_6_count));

          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d",
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(macropad_s3_key_6_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 0%
          green: 0%
          blue: 100%
          brightness: 100%
          effect: "none"
      - homeassistant.action:
          action: assist_satellite.announce
          data:
            message: "Button 6 Pressed"
            preannounce: "false"
            entity_id: assist_satellite.home_assistant_voice_09bf3e_assist_satellite # <-- entity_id moved under data:
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 100%

  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: macropad_s3_key_7
    key: "7"
    name: "MacroPad S3 Key 7"
    on_press:
      - lambda: |-
          id(macropad_s3_key_7_count) += 1;
          id(macropad_s3_key_7_presses_today).publish_state(id(macropad_s3_key_7_count));

          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d",
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(macropad_s3_key_7_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 50%
          green: 0%
          blue: 100%
          brightness: 100%
          effect: "none"
      - homeassistant.action:
          action: assist_satellite.announce
          data:
            message: "Button 7 Pressed"
            preannounce: "false"
            entity_id: assist_satellite.home_assistant_voice_09bf3e_assist_satellite # <-- entity_id moved under data:
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 100%

  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: macropad_s3_key_8
    key: "8"
    name: "MacroPad S3 Key 8"
    on_press:
      - lambda: |-
          id(macropad_s3_key_8_count) += 1;
          id(macropad_s3_key_8_presses_today).publish_state(id(macropad_s3_key_8_count));

          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d",
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(macropad_s3_key_8_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 100%
          green: 0%
          blue: 50%
          brightness: 100%
          effect: "none"
      - homeassistant.action:
          action: assist_satellite.announce
          data:
            message: "Button 8 Pressed"
            preannounce: "false"
            entity_id: assist_satellite.home_assistant_voice_09bf3e_assist_satellite # <-- entity_id moved under data:
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 100%

  - platform: matrix_keypad
    keypad_id: macropad_s3_keypad
    id: macropad_s3_key_9
    key: "9"
    name: "MacroPad S3 Key 9"
    on_press:
      - lambda: |-
          id(macropad_s3_key_9_count) += 1;
          id(macropad_s3_key_9_presses_today).publish_state(id(macropad_s3_key_9_count));

          auto time = id(ha_time).now();
          char timestamp[64];
          snprintf(timestamp, sizeof(timestamp), "%02d/%02d/%04d %02d:%02d:%02d",
                    time.month, time.day_of_month, time.year,
                    time.hour, time.minute, time.second);
          id(macropad_s3_key_9_last_pressed).publish_state(timestamp);
      - light.turn_on:
          id: rgb_led
          red: 100%
          green: 100%
          blue: 100%
          brightness: 100%
          effect: "none"
      - homeassistant.action:
          action: assist_satellite.announce
          data:
            message: "Button 9 Pressed"
            preannounce: "false"
            entity_id: assist_satellite.home_assistant_voice_09bf3e_assist_satellite # <-- entity_id moved under data:
      - delay: 10s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 100%
