# ESPHome ArcadePad S3
# esphome-web-c1e054 Version 2
# File Description: External Package

# [ ==== Globals Info ==== ] #
# globals: [PLACEHOLDER]

# [ ==== Sensor Info ==== ] #
# sensor: [PLACEHOLDER]

# [ ==== Time Info ==== ] #
time:
  - platform: homeassistant
    id: ha_time
    timezone: "America/Chicago"

# [ ==== Web Server Info ==== ] #
web_server:
  port: 80
  version: 3

# [ ==== Buttons ==== ] #
button:
  - platform: factory_reset
    name: "Factory Reset - ArcadePad S3"
    icon: mdi:restart

# [ ==== Binary Sensors ==== ]
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      ignore_strapping_warning: true
      inverted: true
      mode: { input: true, pullup: true }
    name: "Boot Button - ArcadePad S3"
    icon: mdi:gesture-tap-button
  
  - platform: gpio
    id: key_1_arcadepad_s3
    name: "Key 1 - ArcadePad S3"
    icon: mdi:gamepad-circle
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
      inverted: true
    on_multi_click:
      # Single Press
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - script.execute:
              id: handle_key_action
              key_num: 1
      # Press and HOLD
      - timing:
          - ON for 1s to 2s
          - OFF for at least 0.5s
        then:
          - script.execute:
              id: handle_key_hold_action
              key_num: 1
  
  - platform: gpio
    id: key_2_arcadepad_s3
    name: "Key 2 - ArcadePad S3"
    icon: mdi:gamepad-circle-up
    pin:
      number: GPIO5
      mode:
        input: true
        pullup: true
      inverted: true
    on_multi_click:
      # Single Press
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - script.execute:
              id: handle_key_action
              key_num: 2
      # Press and HOLD
      - timing:
          - ON for 1s to 2s
          - OFF for at least 0.5s
        then:
          - script.execute:
              id: handle_key_hold_action
              key_num: 2
  
  - platform: gpio
    id: key_3_arcadepad_s3
    name: "Key 3 - ArcadePad S3"
    icon: mdi:gamepad-circle-right
    pin:
      number: GPIO6
      mode:
        input: true
        pullup: true
      inverted: true
    on_multi_click:
      # Single Press
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - script.execute:
              id: handle_key_action
              key_num: 3
      # Press and HOLD
      - timing:
          - ON for 1s to 2s
          - OFF for at least 0.5s
        then:
          - script.execute:
              id: handle_key_hold_action
              key_num: 3
  
  - platform: gpio
    id: key_4_arcadepad_s3
    name: "Key 4 - ArcadePad S3"
    icon: mdi:nintendo-game-boy
    pin:
      number: GPIO7
      mode:
        input: true
        pullup: true
      inverted: true
    on_multi_click:
      # Single Press
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - script.execute:
              id: handle_key_action
              key_num: 4
      # Press and HOLD
      - timing:
          - ON for 1s to 2s
          - OFF for at least 0.5s
        then:
          - script.execute:
              id: handle_key_hold_action
              key_num: 4
  
  - platform: gpio
    id: key_5_arcadepad_s3
    name: "Key 5 - ArcadePad S3"
    icon: mdi:gamepad-circle-down
    pin:
      number: GPIO15
      mode:
        input: true
        pullup: true
      inverted: true
    on_multi_click:
      # Single Press
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - script.execute:
              id: handle_key_action
              key_num: 5
      # Press and HOLD
      - timing:
          - ON for 1s to 2s
          - OFF for at least 0.5s
        then:
          - script.execute:
              id: handle_key_hold_action
              key_num: 5
  
  - platform: gpio
    id: key_6_arcadepad_s3
    name: "Key 6 - ArcadePad S3"
    icon: mdi:gamepad-circle-left
    pin:
      number: GPIO16
      mode:
        input: true
        pullup: true
      inverted: true
    on_multi_click:
      # Single Press
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - script.execute:
              id: handle_key_action
              key_num: 6
      # Press and HOLD
      - timing:
          - ON for 1s to 2s
          - OFF for at least 0.5s
        then:
          - script.execute:
              id: handle_key_hold_action
              key_num: 6
  
  - platform: gpio
    id: key_7_arcadepad_s3
    name: "Key 7 - ArcadePad S3"
    icon: mdi:gamepad-circle-outline
    pin:
      number: GPIO17
      mode:
        input: true
        pullup: true
      inverted: true
    on_multi_click:
      # Single Press
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - script.execute:
              id: handle_key_action
              key_num: 7
      # Press and HOLD
      - timing:
          - ON for 1s to 2s
          - OFF for at least 0.5s
        then:
          - script.execute:
              id: handle_key_hold_action
              key_num: 7

# [ ==== Text Sensor Info ==== ] #
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address - ArcadePad S3"
      icon: mdi:ip-network
  - platform: version
    name: "ESPHome Version - ArcadePad S3"
    icon: mdi:car-esp

# [ ==== Script Info ==== ] #
script:
  - id: handle_key_action
    parameters:
      key_num: int
    then:
      - light.turn_on:
          id: rgb_led
          red: 0%
          green: 0%
          blue: 100%
          brightness: 100%
      - homeassistant.action:
          action: !lambda |-
            switch(key_num) {
              case 1: return "${key_1_action}";
              case 2: return "${key_2_action}";
              case 3: return "${key_3_action}";
              case 4: return "${key_4_action}";
              case 5: return "${key_5_action}";
              case 6: return "${key_6_action}";
              case 7: return "${key_7_action}";
            }
            return "";
          data:
            entity_id: !lambda |-
              switch(key_num) {
                case 1: return "${key_1_entity}";
                case 2: return "${key_2_entity}";
                case 3: return "${key_3_entity}";
                case 4: return "${key_4_entity}";
                case 5: return "${key_5_entity}";
                case 6: return "${key_6_entity}";
                case 7: return "${key_7_entity}";
              }
              return "";
      - delay: 5s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 100%

  - id: handle_key_hold_action
    parameters:
      key_num: int
    then:
      - light.turn_on:
          id: rgb_led
          red: 100%
          green: 100%
          blue: 100%
          brightness: 100%
      - homeassistant.action:
          action: !lambda |-
            switch(key_num) {
              case 1: return "${key_1_action_hold}";
              case 2: return "${key_2_action_hold}";
              case 3: return "${key_3_action_hold}";
              case 4: return "${key_4_action_hold}";
              case 5: return "${key_5_action_hold}";
              case 6: return "${key_6_action_hold}";
              case 7: return "${key_7_action_hold}";
            }
            return "";
          data:
            entity_id: !lambda |-
              switch(key_num) {
                case 1: return "${key_1_entity_hold}";
                case 2: return "${key_2_entity_hold}";
                case 3: return "${key_3_entity_hold}";
                case 4: return "${key_4_entity_hold}";
                case 5: return "${key_5_entity_hold}";
                case 6: return "${key_6_entity_hold}";
                case 7: return "${key_7_entity_hold}";
              }
              return "";
      - delay: 5s
      - light.turn_on:
          id: rgb_led
          effect: rainbow
          brightness: 100%
